# Generated by Django 3.2.5 on 2021-07-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Slug (shortened URL without http://domain/ part)')),
                ('url', models.URLField(verbose_name='Shortened URL')),
            ],
        ),
    ]
