# Generated by Django 3.2.5 on 2021-07-20 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210719_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation time'),
            preserve_default=False,
        ),
    ]
