version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - backend-socket:/run/backend
  nginx:
    build: ./frontend
    volumes:
      - backend-socket:/run/backend
    ports:
      - "80:80"

volumes:
  backend-socket:
